version: '3.9'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - nodl-net

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "3001:3000"
    depends_on:
      - api
    networks:
      - nodl-net

  miniapp:
    build:
      context: ./apps/miniapp
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "3002:3000"
    depends_on:
      - api
    networks:
      - nodl-net

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
      - miniapp
      - api
    networks:
      - nodl-net

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodl
      MONGO_INITDB_ROOT_PASSWORD: nodl
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - nodl-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - nodl-net

volumes:
  mongo_data:

networks:
  nodl-net:
    driver: bridge
